### ISSUE TITLE
First Commission (pre-milestone)

### ISSUE THREAD

**Issue by cemreefe** [bounswe/bounswe2020group6#168]
We will carry out our planned tasks on the [Project Plan](https://github.com/bounswe/bounswe2020group6/blob/master/Files/Templates/Project%20Plan1.pdf). The dates given may vary. 

For now, it is decided that the team carry out tasks 1-19, 

### 🔮 The back-end team should implement:
- [x]  Login and sign up functionality
- [x]  Tagging system regarding research interests
- [x]  The parts about research area, recent publications ...
- [x]  Paper/project creation
- [x]  Paper/project editing 
- [x]  Search functionalities

### 🌺 The front-end  team should implement: ( #172  )
- [x]  Login and sign up pages
- [x]  Front-end for the tagging system of research interests
- [x]  Research area and recent publications display components
- [x]  Paper/project creation page
- [x]  Paper/project edit page
- [x]  Search bar and results page

### 🤖 The android  team should implement: ( #170 )
- [x]  Login and sign up screens
- [x]  The tagging system of research interests
- [x]  Research area and recent publications display components
- [x]  Search bar and results screen
- [x]  Paper/project edit screen
- [x]  Paper/project creation screen

### 📎 Group effort
- [x]  The project, although incomplete, should be deployed live within the first two weeks.

**Comment by FarukOzderim** [comment]
Milestone has been completed successfully.
