### ISSUE TITLE
Android Dev - Modifications before Milestone

### ISSUE THREAD

**Issue by gulperii** [bounswe/bounswe2020group6#183]
After meeting with the customer, we have minor modifications to implement:

- [x] "Publications" will be changed to "Project"

- [x] Anything related to "Paper" will be deleted. 

- [x] In Sign up page, ask Name - Surname fields before verification.

- [x] Stars in profile page will be changed into upvotes.

- [ ] Design of the project (color palette, background images, fonts ) will be improved.

**Comment by FarukOzderim** [comment]
@gulperii @Tubagc @cihatkapusuz @DogukanKalkan  
I think this issue might be completed.

**Comment by cihatkapusuz** [comment]
Major tasks are done but design related additions are not done yet. However, we can close this issue and mention about it in another issue. Thanks for reminding.
