### ISSUE TITLE
Milestone Report 1 Deadline 29/11/2020 23.55

### ISSUE THREAD

**Issue by Tubagc** [bounswe/bounswe2020group6#210]
### Task division of Milestone 1 Report

@Tubagc 
- [x] Table of content.

@cihatkapusuz 
- [x] Executive Summary: Summary of project status and any changes that are planned for moving forward.
- [x] Assessment of the customer presentation. What did you learn from your interaction about the status and direction of your project? Also, did you learn anything about presenting? Difficulties? What went well, what needs improvement for next time.

@aliramazanmert 
- [x] A detailed explanation of the challenges you met during the deployment, dockerizing, and CI/CD processes.

@FarukOzderim 
- [x] Requirements. You should highlight and reason all changes that you have done in the CMPE451 semester.

@DogukanKalkan @UkcaGreen @dogruomerfaruk 
- [x] Design documents. You should highlight and reason all changes that you have done in the CMPE451 semester.

@isiktashamza
- [x] API documentation (Do not just put the link to your documentation. You need to document within the report.).

@Tubagc
- [x] Project plan (in tabular format; you may omit Gantt timelines and display dates/durations/assignees/predecessors only as a text for readability. Unreadable plans will NOT be graded.).

@cemreefe @cihatkapusuz 
- [x] User scenarios you presented during the milestone presentation.

@gulperii @EnesToptas @cemreefe
The code structure and group process should be documented, for example, if each feature is a branch and what are the branches, how are pull requests used, etc.
  - [x] Frontend
  - [x] Backend
  - [x] Mobile

### These will be done by every single member of the team.

- [x] Evaluation of tools and managing the project. This is a lesson learned from the project development decisions made so far. Tools are for planning, IDE, frameworks, and everything. The management is the process used by the team, including how the tools are being effectively utilized. If there are some aspects that are not working out, what kind of changes are planned.

- [x] List and status of deliverables.

- [x] Evaluation of the status of deliverables and their impact on the plan. 

- [x] A summary of coding work done by each team member (in tabular format).

**Comment by cihatkapusuz** [comment]
Android user scenario part is done in the Milestone 1 Report. @cemreefe You can check the related box after completing frontend user scenario part.

**Comment by cihatkapusuz** [comment]
I wrote the assessment part of the Milestone 1 Report, and I am looking for feedback about my part. Also, I wrote a summary of the coding work part that is about me.

**Comment by cemreefe** [comment]
> Android user scenario part is done in the Milestone 1 Report. @cemreefe You can check the related box after completing frontend user scenario part.

I completed my part as well, and documented the web-app user scenario. I'm marking the related task as complete.

**Comment by aliramazanmert** [comment]
I wrote the deployment/dockerizing/CICD part and also my code contribution part

**Comment by cemreefe** [comment]
I completed
*  Evaluation of tools and managing the project. 
* List and status of deliverables for frontend. (not final)
* Evaluation of the status of deliverables and their impact on the plan.

**Comment by Tubagc** [comment]
- I created a table of content.
- I wrote the summary of my part of the coding work.
- I added the project plan and added an explanation
- I wrote some parts of the evaluation of tools and project management
- I wrote the mobile part of the deliverables and some evaluation for that.

**Comment by FarukOzderim** [comment]
-I wrote the requirements and its changes.
-I wrote my part in summary of coding work.
-I wrote some evaluations for backend in evaluation of tools and project management.

**Comment by gulperii** [comment]
- I completed my part in the summary of coding work.
- I wrote the code structure and group process documentation for the backend team.
- I wrote some evaluations on the project management

**Comment by isiktashamza** [comment]
- I wrote API documentation
- I completed my part in the summary of coding work.

**Comment by UkcaGreen** [comment]
1. I wrote sequence diagrams part of the design documents.
2. Revieved the used tools by the frontend team.
3. Revieved the deliverables created by the frontend team.
4. I wrote my part in the code work summary part.

**Comment by hazerb** [comment]
I completed missing parts of requirements section,
wrote evaluation on project management,
reviewed the tools used by backend team,
wrote my part in summary of coding work

**Comment by EnesToptas** [comment]
- I wrote Backend part of deliverables
- I wrote Backend part of evaluation of the deliverables
- I wrote the code structure and group process of the backend team. How we utilized branches and pull requests.
- I wrote my part of the code work summary part.

**Comment by cihatkapusuz** [comment]
Milestone Report 1 prepared in a given time and @UkcaGreen put it on our wiki page. Also he sent the Milestone Report 1 to our customer.
