### ISSUE TITLE
MILESTONE 2 PLAN. 

### ISSUE THREAD

**Issue by isiktashamza** [bounswe/bounswe2020group6#217]
We will carry out our planned tasks on the [Project Plan](https://github.com/bounswe/bounswe2020group6/blob/master/Files/Templates/Project%20Plan1.pdf). The dates given may vary. 

For now, it is decided that the team carry out tasks up to 50, 

### 🔮 The back-end team should implement:
- [x]  inviting a user, accepting and rejecting requests
- [x]  seeing , accepting, and rejecting requests
- [x]  status of papers/projects
- [x]  home page
- [x]  google scholar linking
- [x]  simultaneous document upload
- [x] filtering system 
- [x] follow functionality
- [x] autocomplete functionality

### 🌺 The front-end  team should implement: 
- [x]  inviting a user, accepting and rejecting requests
- [x]  seeing , accepting, and rejecting requests
- [x]  Logout
- [x]  status of papers/projects
- [x]  home page
- [x]  google scholar linking
- [x]  simultaneous document preparation
- [x] filtering system 
- [x] follow functionality

### 🤖 The android  team should implement: 
- [ ]  inviting a user, accepting and rejecting requests
- [x]  seeing , accepting, and rejecting requests
- [x]  Logout
- [x]  status of papers/projects
- [x]  home page
- [x]  google scholar linking
- [ ]  simultaneous document preparation
- [x] filtering system 
- [x] follow functionality

**Comment by cemreefe** [comment]
Logout feature is functional on frontend.

**Comment by FarukOzderim** [comment]
get and add endpoints are added for Autocomplete feature. #234

**Comment by isiktashamza** [comment]
I implemented all follow-related endpoints

**Comment by hazerb** [comment]
implemented status of paper/projects , and request related endpoints

**Comment by EnesToptas** [comment]
i implemented google scholar linking

**Comment by isiktashamza** [comment]
I ımplemented a basic filtering system in search so that user and project search can be separated and private projects are not displayed in search results

**Comment by isiktashamza** [comment]
I ,@EnesToptas , and @hazerb implemented /home/posts and /home/users endpoints. We also add some utility functions for future usage.

**Comment by Tubagc** [comment]
I implemented linking Google Scholar linking for mobile.

**Comment by Tubagc** [comment]
I added home functionality to mobile

**Comment by cihatkapusuz** [comment]
Simultaneous document preparation for mobile is removed from our Milestone 2 plan, because it can be done through web app and adding this functionality is very hard task. Also it would not be user friendly. Preparing a document through mobile and adding it into the system is not very easy on mobile. Instead of addition of new files to system via android, user will be able to see the files in the projects
