### ISSUE TITLE
Milestone 2 Report Deadline: 05.01.2021 23:55

### ISSUE THREAD

**Issue by Tubagc** [bounswe/bounswe2020group6#344]
### Task division of Milestone 2 Report

@cihatkapusuz 
- [x] Executive Summary: Summary of project status and any changes that are planned for moving forward.

@DogukanKalkan @cemreefe 
- [x] Assessment of the customer presentation. What did you learn from your interaction about the status and direction of your project? Also, did you learn anything about presenting? Difficulties? What went well, what needs improvement for next time.

@aliramazanmert 
- [x] A detailed explanation of the challenges you met during the deployment, dockerizing, and CI/CD processes.

@DogukanKalkan @UkcaGreen @dogruomerfaruk 
- [x] Design documents. You should highlight and reason all changes that you have done in the CMPE451 semester.

@isiktashamza
- [x] API documentation (Do not just put the link to your documentation. You need to document within the report.).

@Tubagc
- [x] Project plan (in tabular format; you may omit Gantt timelines and display dates/durations/assignees/predecessors only as a text for readability. Unreadable plans will NOT be graded.).

@cemreefe @DogukanKalkan 
- [x] User scenarios you presented during the milestone presentation.

@gulperii @EnesToptas @cemreefe
The code structure and group process should be documented, for example, if each feature is a branch and what are the branches, how are pull requests used, etc.
  - [x] Frontend
  - [x] Backend
  - [x] Mobile

### These will be done by every single member of the team.

- [x] Evaluation of tools and managing the project. This is a lesson learned from the project development decisions made so far. Tools are for planning, IDE, frameworks, and everything. The management is the process used by the team, including how the tools are being effectively utilized. If there are some aspects that are not working out, what kind of changes are planned.

- [x] List and status of deliverables.

- [x] Evaluation of the status of deliverables and their impact on the plan. 

- [x] A summary of coding work done by each team member (in tabular format).

- [x] Each team member should explain the unit tests committed by him/her by referring to the commit SHA (in a separate subsection for each member under the Unit Tests Section)

**Comment by gulperii** [comment]
I have documented the code structure and group process for mobile team. 
I have added my review on project management.
I have added my code contribution

**Comment by Tubagc** [comment]
I added the project plan.
I added my code contribution.
I added my evaluation of deliverables.

**Comment by cemreefe** [comment]
I added the scenario we used in this presentation. However I am yet to add scenario images since we haven't taken any during the presentation and/or rehearsals.

**Comment by FarukOzderim** [comment]
Added review on project management.
Added code contribution

**Comment by aliramazanmert** [comment]
Added my code contribution
Added dockerizing/ci-cd/deployment part
Added review on project management
Added evaluation for tools we use in frontend
added evaluation of deliverables but we need further deliverables i suppose, it is not updated from the report 1 yet.

**Comment by cihatkapusuz** [comment]
I added executive summary. 
I added my code contribution.
I added evaluation of tools and deliverables.

**Comment by isiktashamza** [comment]
I added API documentation
I added my code contribution

**Comment by hazerb** [comment]
Added review on deliverables
Added my code contribution

**Comment by EnesToptas** [comment]
I have documented the code structure and group process for the backend team.
I have added my review on project management.
I have added my code contribution.

**Comment by UkcaGreen** [comment]
Added my code contribution. 
Added/updated status of the deliverables.

**Comment by cihatkapusuz** [comment]
Milestone report 2 submitted on time.
