### ISSUE TITLE
Final Milestone Report Deadline: 31.01.2021 23.00

### ISSUE THREAD

**Issue by Tubagc** [bounswe/bounswe2020group6#444]
all members
- [ ] Final project assessment (Final Milestone -- assesses the whole process such as lessons learned)
- [ ] Status of deliverables
- [ ] A summary of coding work done by each team member (in tabular format)
- [ ] Unit tests (each team member should explain the unit tests committed by him/her by referring to the commit SHA)
- [ ] Activity stream implementation & W3C standard compliance
- [x] Assessment of the final customer presentation

backend team
- [ ] API documentation

@FarukOzderim 
- [x] Requirements

@DogukanKalkan 
- [ ] All design documents (diagrams, mockups etc.)

 frontend team
- [x] User manual

mobile team
- [x] User manual

backend team
- [x] System manual

@Tubagc 
- [x] Project Plan (simplified version in a report-friendly format)

**Comment by UkcaGreen** [comment]
I have written the **_assessment of the final customer presentation_**.

**Comment by EnesToptas** [comment]
I have written the system manual for the backend.

**Comment by FarukOzderim** [comment]
I have written the requirements.
I have written summary of my code contribution.

**Comment by cihatkapusuz** [comment]
I have written my part of the report
