### ISSUE TITLE
Fixing Project Plan According To Feedback 

### ISSUE THREAD

**Issue by FarukOzderim** [bounswe/bounswe2020group6#91]
Here are the tasks for the feedback, please mark the completed tasks and comment you completed the task.
Assigneess: Everyone
_Deadline: 28.04.2020 23.55_

- [x] Create Ram Chart
- [x] Create wiki page for the project plan
- [x] Fix typo for "frontend", "forend"
- [x] Change Major Task Of Following
Why does “deciding on forend backed (typo here) routines” is covered by the major task of Project Plan?
- [x] 6 days for meeting notes, even 13 days for it, but 3 days for creating use case diagram?
- [x] Remove unrelated tasks. 
I think “assigning issues” or “meeting with customer” are not part of a plan, they are not tasks to be mentioned in the plan. Besides, some task names should be redefined such as “removing some parts from requirements”. It seems quite informal and ambiguous.
- [x] Create more detailed plan for CMPE451/implementation. Also Frontend and Backend should not be seperate.
Yes, it is stated that CMPE451/implementation part should be prepared in a high-level manner, but this is very high-level :) At least some details about the tasks related to your requirements are expected, such as “implementing the search functionality”, “implementing the signup facility” and so on. The implementation tasks in your plan does not differ much from not defining the implementation-related tasks at all.
One can start implementing frontend before completing the backend. In other words, backend is not a prerequisite of the frontend, even though they are highly related.

**Comment by FarukOzderim** [comment]
2,3,4,5,6 are completed.

**Comment by FarukOzderim** [comment]
Ram Chart will be created by Ahmet Berat

**Comment by FarukOzderim** [comment]
CMPE451 plan will be written by Hazer, Enes, Gülperi, Hamza
