### ISSUE TITLE
Milestone 1 Report

### ISSUE THREAD

**Issue by FarukOzderim** [bounswe/bounswe2020group6#96]
Milestone Report 1 will be written by all team members.
_Deadline: 03.05.2020 23:55_

-Everyone will fill personal contrubition.

- [x] Old Works and Documents Will Be Written In Milestone:
Salih

Evaluation of tools and processes:
- [x] Github –  Doğu
- [x] ProjectLibre - Ömer
- [x] MockFlow - Tuba
- [ ] LucidChart - Cemre
- [x] Slack - Gülperi
- [x] Zoom - Enes

- [x] Executive Summary, summary of Project Status, planned for Moving Forward:
Emilcan,Hamza

- [x] Evaluation of the status of deliverables and its impact on your project plan:
Tuba

**Comment by UkcaGreen** [comment]
Executive Summary, Summary of Project Status, Planned for Moving Forward parts are written in the milestone 1 report.

**Comment by gulperii** [comment]
Slack evaluation and personal contribution are added

**Comment by Tubagc** [comment]
Evaluation of the status of deliverables and its impact on your project plan are added.
Evaluation of Mockflow is added.
Presonal Contribution is added.

**Comment by DogukanKalkan** [comment]
Github evaluation and personal contribution have been added.
